using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;
using NUnit.Framework;

namespace TumbangPreso.Tests
{
    /// <summary>
    /// Every shipped map's colour grade, asserted as a band rather than as an exact value.
    ///
    /// ⚠️⚠️ THIS EXISTS BECAUSE ONE MISTYPED CONSTANT SHIPPED A MAP THAT RENDERED BLACK, AND
    /// NOTHING IN THE HARNESS COULD SEE IT. 🧑, off the built .exe: *"New map is just black wtf,
    /// i cant see shit properly"*.
    ///
    /// `IlalimNgTulayBuilder` set the map's tonemap exposure to **0.15** where Eskinita uses
    /// **0.92** and Bayan Plaza uses **0** (tonemap off). `ColourGrade.shader` multiplies the
    /// whole frame by that number before the ACES curve, so it is the single value in a map that
    /// can darken everything at once. Running the shader's own arithmetic, a mid-grey linear 0.5
    /// came out at 0.0391 against Eskinita's 0.4088, and the frame contrast of 1.12 then drove
    /// every linear value below **0.59** to pure black.
    ///
    /// ⚠️ FOUR SIGNED-OFF SHOWCASE RENDERS MISSED IT, and so did Core, EditMode, PlayMode,
    /// `ArenaCheck`, `AudioCueCheck`, `MapGeometryCheck` and `SceneScriptCheck`. The grade is a
    /// CAMERA pass, so it is invisible to every check that measures the scene graph, and the
    /// defect is worst under the LRT deck, which is not where a showcase camera points.
    /// `MapGeometryCheck` measures geometry and cannot see brightness at all.
    ///
    /// ⚠️⚠️ IT READS THE SCENES AS TEXT, THE SAME REASON `SceneScriptCheck` DOES. The value that
    /// ships is the SERIALIZED one. A builder can be corrected and the scene left stale, which is
    /// exactly the split that let this reach a player: the map is generated by
    /// `IlalimNgTulayBuilder` but what the player loads is `IlalimNgTulay.unity`. Opening the
    /// scene through the editor would also drag in the whole map and cost a Unity launch this
    /// suite does not need.
    ///
    /// `docs/Hero_Strike_Balance.md` § 3.0 carries the full derivation.
    /// </summary>
    public sealed class MapGradeSanityTests
    {
        private const string MapDirectory = "Assets/TumbangPreso/Scenes/Maps";

        /// <summary>
        /// The legal band for a NON-ZERO tonemap exposure.
        ///
        /// ⚠️ ZERO IS SEPARATELY LEGAL AND MEANS "NO TONEMAP", matching a Godot Environment whose
        /// `tonemap_mode` is 0 (LINEAR). Bayan Plaza is one of those, so the assertion cannot be
        /// a simple range: it is "off, or inside the band", and a value between the two is the
        /// signature of a typo rather than of a decision.
        ///
        /// ⚠️ THE BAND IS SET FROM WHAT THE IMPORTER CAN EMIT, not from taste.
        /// `TscnImporter.cs` reads `tonemapMode > 0 ? SubProp(env, "tonemap_exposure", 1.0f) : 0f`
        /// and Godot's own default is 1.0, so every honestly imported map lands at or near 1.0.
        /// 0.60 to 1.30 admits a deliberate darker or brighter map and still rejects the 0.15
        /// that shipped, which is more than four times below the floor.
        /// </summary>
        private const float MinExposure = 0.60f;
        private const float MaxExposure = 1.30f;

        /// <summary>
        /// ⚠️ A GRADE CAN ALSO GO BLACK THROUGH CONTRAST, so that is bounded too. The BCS step is
        /// `lerp(0.5, c, contrast)`, which drives everything below mid-grey further down and
        /// reaches zero at `c = 0.5 - 0.5 / contrast`. At the shipped 1.12 that is 0.054, so a
        /// contrast much past this turns a merely dark frame into a crushed one. The three maps
        /// ship 1.03, 1.07 and 1.12.
        /// </summary>
        private const float MaxContrast = 1.35f;

        private static readonly Regex GradeBlock = new Regex(
            @"_brightness:\s*(?<b>[-0-9.eE+]+)\s*\r?\n"
            + @"\s*_contrast:\s*(?<c>[-0-9.eE+]+)\s*\r?\n"
            + @"\s*_saturation:\s*(?<s>[-0-9.eE+]+)\s*\r?\n"
            + @"\s*_exposure:\s*(?<e>[-0-9.eE+]+)\s*\r?\n"
            + @"\s*_white:\s*(?<w>[-0-9.eE+]+)",
            RegexOptions.Compiled);

        private static IEnumerable<string> MapScenes()
        {
            if (!Directory.Exists(MapDirectory)) yield break;

            foreach (string path in Directory.GetFiles(MapDirectory, "*.unity"))
                yield return path;
        }

        [Test]
        public void EveryMapGradeIsInsideTheLegalBand()
        {
            var findings = new List<string>();
            int graded = 0;

            foreach (string path in MapScenes())
            {
                string name = Path.GetFileName(path);
                var match = GradeBlock.Match(File.ReadAllText(path));

                // A map is allowed to carry no MapGrade at all. Only a grade that EXISTS and is
                // out of band is a fault; a missing one renders ungraded, which is visible but
                // never black.
                if (!match.Success) continue;

                graded++;

                float exposure = float.Parse(match.Groups["e"].Value);
                float contrast = float.Parse(match.Groups["c"].Value);

                if (exposure != 0.0f && (exposure < MinExposure || exposure > MaxExposure))
                {
                    findings.Add(
                        $"{name}: tonemap exposure {exposure} is neither 0 (tonemap off) nor "
                        + $"inside {MinExposure} to {MaxExposure}. ColourGrade.shader multiplies "
                        + "the whole frame by this before the ACES curve, so a value this far "
                        + "down renders the map black. Eskinita uses 0.92.");
                }

                if (contrast > MaxContrast)
                {
                    findings.Add(
                        $"{name}: contrast {contrast} is above {MaxContrast}. lerp(0.5, c, "
                        + "contrast) drives everything under mid-grey toward zero, so a high "
                        + "contrast crushes a dark frame to pure black.");
                }
            }

            Assert.Greater(graded, 0,
                "no map scene carried a MapGrade block at all, so this test asserted nothing. "
                + "Either the maps moved out of " + MapDirectory + " or the serialized field "
                + "names changed, and in both cases this check is silently dead.");

            Assert.IsEmpty(findings, string.Join("\n", findings));
        }

        /// <summary>
        /// ⚠️⚠️ THE BUILDER AND THE SCENE ARE TWO PLACES TO WRITE THE SAME NUMBER, AND THE SPLIT
        /// IS WHAT LET THE FAULT REACH A PLAYER. Ilalim ng Tulay is generated by
        /// `IlalimNgTulayBuilder.MapGrade.Set(...)`, but the player loads `IlalimNgTulay.unity`,
        /// so correcting the builder and forgetting to rebuild the scene fixes nothing at all
        /// while looking like it did.
        ///
        /// This asserts the pair agrees, the same way
        /// `HeroPresentationTests.TelegraphsMatchWhatTheAbilityPlaces` asserts a telegraph
        /// against what its ability actually spawns.
        /// </summary>
        /// <summary>
        /// The overclock window's copy of the pass length still matches the train that produces
        /// it.
        ///
        /// ⚠️⚠️ IT IS A COPY ON PURPOSE AND THAT IS EXACTLY WHY IT NEEDS A TEST.
        /// `OverheadPassWindow` is a plain static that has to answer before any `LrtTrainFlyby`
        /// exists, so it cannot read the component; it carries `PassSeconds = 2.70` and derives
        /// `OverclockRate` from it. `LrtTrainFlyby` derives the same 2.70 from its consist length
        /// and its speed. Change the train's `Speed` from 18 and the two disagree, the saving
        /// silently stops being `OverclockSeconds`, and the one number a designer authored is
        /// quietly no longer the number the game delivers. That is precisely the class of drift
        /// `docs/Hero_Strike_Balance.md` § 4.5 wanted the flat figure to be immune to.
        ///
        /// ⚠️ IT READS THE FLYBY AS TEXT, like the builder-versus-scene test below, because the
        /// fields are serialised defaults on a component this suite does not instantiate.
        /// </summary>
        [Test]
        public void TheOverclockWindowAgreesWithTheTrainThatCausesIt()
        {
            const string flyby = "Assets/TumbangPreso/Runtime/Map/LrtTrainFlyby.cs";
            Assert.IsTrue(File.Exists(flyby), flyby + " is missing");

            string text = File.ReadAllText(flyby);

            var speed = Regex.Match(text, @"public float Speed\s*=\s*([0-9.]+)f");
            var halfZ = Regex.Match(text, @"public float OverheadHalfZ\s*=\s*([0-9.]+)f");

            Assert.IsTrue(speed.Success, "LrtTrainFlyby no longer declares Speed");
            Assert.IsTrue(halfZ.Success, "LrtTrainFlyby no longer declares OverheadHalfZ");

            float v = float.Parse(speed.Groups[1].Value,
                                  System.Globalization.CultureInfo.InvariantCulture);
            float z = float.Parse(halfZ.Groups[1].Value,
                                  System.Globalization.CultureInfo.InvariantCulture);

            // ⚠️ THE CONSIST LENGTH IS ALREADY INSIDE `OverheadHalfZ` AND ADDING IT AGAIN IS
            // THE MISTAKE THIS COMMENT EXISTS TO STOP. The field's own note reads
            // `(33.0 + 15.6) / 18 = 2.70 s`, which lists wall length 33.0 plus consist 15.6, and
            // that sum IS 48.6 = 2 x 24.3. So the window is the range the flag is true over,
            // divided by the speed, and nothing else. The first version of this test added the
            // 15.6 a second time and reported 3.57 s against a correct 2.70.
            float pass = (z * 2.0f) / v;

            Assert.AreEqual(pass, OverheadPassWindow.PassSeconds, 0.02f,
                $"the train is overhead for {pass:F2} s but OverheadPassWindow says " +
                $"{OverheadPassWindow.PassSeconds:F2} s, so the window no longer takes " +
                $"{OverheadPassWindow.OverclockSeconds:F2} s off a cooldown.");

            // ⚠️ AND THE DERIVED RATE STILL DELIVERS THE AUTHORED SAVING. A rate r held for a
            // window W advances the clock by W * r, so it saves W * (r - 1).
            float saved = OverheadPassWindow.PassSeconds * (OverheadPassWindow.OverclockRate - 1.0f);
            Assert.AreEqual(OverheadPassWindow.OverclockSeconds, saved, 0.01f,
                "the derived rate no longer saves the seconds it was authored to save");
        }

        [Test]
        public void TheIlalimBuilderAgreesWithTheSceneItGenerates()
        {
            const string builder = "Assets/TumbangPreso/Editor/MapKit/IlalimNgTulayBuilder.cs";
            const string scene = MapDirectory + "/IlalimNgTulay.unity";

            Assert.IsTrue(File.Exists(builder), builder + " is missing");
            Assert.IsTrue(File.Exists(scene), scene + " is missing");

            var call = Regex.Match(
                File.ReadAllText(builder),
                @"grade\.Set\(\s*(?<b>[-0-9.f]+)\s*,\s*(?<c>[-0-9.f]+)\s*,"
                + @"\s*(?<s>[-0-9.f]+)\s*,\s*(?<e>[-0-9.f]+)\s*,\s*(?<w>[-0-9.f]+)\s*\)");

            Assert.IsTrue(call.Success,
                "could not find the grade.Set(...) call in " + builder
                + ". If it was renamed, rename it here too rather than deleting this test: the "
                + "builder-versus-scene split is the fault this covers.");

            var baked = GradeBlock.Match(File.ReadAllText(scene));
            Assert.IsTrue(baked.Success, "no MapGrade block found in " + scene);

            foreach (string key in new[] { "b", "c", "s", "e", "w" })
            {
                float fromBuilder = float.Parse(call.Groups[key].Value.TrimEnd('f'));
                float fromScene = float.Parse(baked.Groups[key].Value);

                Assert.AreEqual(fromBuilder, fromScene, 0.0005f,
                    $"grade component '{key}' is {fromBuilder} in the builder and {fromScene} in "
                    + "the scene. The SCENE is what ships. Re-run IlalimNgTulayPipeline, or "
                    + "correct whichever of the two is wrong.");
            }
        }
    }
}
